import type { Metadata } from 'next';

import * as s from './layout.css';

import '@/styles/global.css';

export const metadata: Metadata = {
  title: '📈',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning>
      <body className={s.layout}>{children}</body>
    </html>
  );
}
